/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicRefundPolicyRouteImport } from './routes/_public/refund-policy'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicHomeRouteImport } from './routes/_public/home'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ProtectedWithdrawalHistoryRouteImport } from './routes/_protected/withdrawal-history'
import { Route as ProtectedUsersRouteImport } from './routes/_protected/users'
import { Route as ProtectedUserTicketRouteImport } from './routes/_protected/user-ticket'
import { Route as ProtectedPaymentsRouteImport } from './routes/_protected/payments'
import { Route as ProtectedPaymentSuccessRouteImport } from './routes/_protected/payment-success'
import { Route as ProtectedPaymentHistoryRouteImport } from './routes/_protected/payment-history'
import { Route as ProtectedOrdersRouteImport } from './routes/_protected/orders'
import { Route as ProtectedMyusersRouteImport } from './routes/_protected/myusers'
import { Route as ProtectedMycontactRouteImport } from './routes/_protected/mycontact'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedCheckoutRouteImport } from './routes/_protected/checkout'
import { Route as ProtectedCartRouteImport } from './routes/_protected/cart'
import { Route as ProtectedAllUsersRouteImport } from './routes/_protected/all-users'
import { Route as ProtectedAllOrdersRouteImport } from './routes/_protected/all-orders'
import { Route as ProtectedAdminTicketRouteImport } from './routes/_protected/admin-ticket'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin-dashboard'
import { Route as ProtectedAddcoursesRouteImport } from './routes/_protected/addcourses'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as PublicCoursesIndexRouteImport } from './routes/_public/courses/index'
import { Route as ProtectedMycoursesIndexRouteImport } from './routes/_protected/mycourses/index'
import { Route as PublicCoursesIdRouteImport } from './routes/_public/courses/$id'
import { Route as ProtectedMycoursesIdRouteImport } from './routes/_protected/mycourses/$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRefundPolicyRoute = PublicRefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHomeRoute = PublicHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedWithdrawalHistoryRoute =
  ProtectedWithdrawalHistoryRouteImport.update({
    id: '/withdrawal-history',
    path: '/withdrawal-history',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUserTicketRoute = ProtectedUserTicketRouteImport.update({
  id: '/user-ticket',
  path: '/user-ticket',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentsRoute = ProtectedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentSuccessRoute = ProtectedPaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentHistoryRoute = ProtectedPaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrdersRoute = ProtectedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyusersRoute = ProtectedMyusersRouteImport.update({
  id: '/myusers',
  path: '/myusers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMycontactRoute = ProtectedMycontactRouteImport.update({
  id: '/mycontact',
  path: '/mycontact',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCheckoutRoute = ProtectedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCartRoute = ProtectedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAllUsersRoute = ProtectedAllUsersRouteImport.update({
  id: '/all-users',
  path: '/all-users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAllOrdersRoute = ProtectedAllOrdersRouteImport.update({
  id: '/all-orders',
  path: '/all-orders',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminTicketRoute = ProtectedAdminTicketRouteImport.update({
  id: '/admin-ticket',
  path: '/admin-ticket',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAddcoursesRoute = ProtectedAddcoursesRouteImport.update({
  id: '/addcourses',
  path: '/addcourses',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const PublicCoursesIndexRoute = PublicCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedMycoursesIndexRoute = ProtectedMycoursesIndexRouteImport.update({
  id: '/mycourses/',
  path: '/mycourses/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicCoursesIdRoute = PublicCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedMycoursesIdRoute = ProtectedMycoursesIdRouteImport.update({
  id: '/mycourses/$id',
  path: '/mycourses/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/addcourses': typeof ProtectedAddcoursesRoute
  '/admin-dashboard': typeof ProtectedAdminDashboardRoute
  '/admin-ticket': typeof ProtectedAdminTicketRoute
  '/all-orders': typeof ProtectedAllOrdersRoute
  '/all-users': typeof ProtectedAllUsersRoute
  '/cart': typeof ProtectedCartRoute
  '/checkout': typeof ProtectedCheckoutRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/mycontact': typeof ProtectedMycontactRoute
  '/myusers': typeof ProtectedMyusersRoute
  '/orders': typeof ProtectedOrdersRoute
  '/payment-history': typeof ProtectedPaymentHistoryRoute
  '/payment-success': typeof ProtectedPaymentSuccessRoute
  '/payments': typeof ProtectedPaymentsRoute
  '/user-ticket': typeof ProtectedUserTicketRoute
  '/users': typeof ProtectedUsersRoute
  '/withdrawal-history': typeof ProtectedWithdrawalHistoryRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/home': typeof PublicHomeRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/refund-policy': typeof PublicRefundPolicyRoute
  '/terms': typeof PublicTermsRoute
  '/mycourses/$id': typeof ProtectedMycoursesIdRoute
  '/courses/$id': typeof PublicCoursesIdRoute
  '/mycourses': typeof ProtectedMycoursesIndexRoute
  '/courses': typeof PublicCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/addcourses': typeof ProtectedAddcoursesRoute
  '/admin-dashboard': typeof ProtectedAdminDashboardRoute
  '/admin-ticket': typeof ProtectedAdminTicketRoute
  '/all-orders': typeof ProtectedAllOrdersRoute
  '/all-users': typeof ProtectedAllUsersRoute
  '/cart': typeof ProtectedCartRoute
  '/checkout': typeof ProtectedCheckoutRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/mycontact': typeof ProtectedMycontactRoute
  '/myusers': typeof ProtectedMyusersRoute
  '/orders': typeof ProtectedOrdersRoute
  '/payment-history': typeof ProtectedPaymentHistoryRoute
  '/payment-success': typeof ProtectedPaymentSuccessRoute
  '/payments': typeof ProtectedPaymentsRoute
  '/user-ticket': typeof ProtectedUserTicketRoute
  '/users': typeof ProtectedUsersRoute
  '/withdrawal-history': typeof ProtectedWithdrawalHistoryRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/home': typeof PublicHomeRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/refund-policy': typeof PublicRefundPolicyRoute
  '/terms': typeof PublicTermsRoute
  '/mycourses/$id': typeof ProtectedMycoursesIdRoute
  '/courses/$id': typeof PublicCoursesIdRoute
  '/mycourses': typeof ProtectedMycoursesIndexRoute
  '/courses': typeof PublicCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/addcourses': typeof ProtectedAddcoursesRoute
  '/_protected/admin-dashboard': typeof ProtectedAdminDashboardRoute
  '/_protected/admin-ticket': typeof ProtectedAdminTicketRoute
  '/_protected/all-orders': typeof ProtectedAllOrdersRoute
  '/_protected/all-users': typeof ProtectedAllUsersRoute
  '/_protected/cart': typeof ProtectedCartRoute
  '/_protected/checkout': typeof ProtectedCheckoutRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/mycontact': typeof ProtectedMycontactRoute
  '/_protected/myusers': typeof ProtectedMyusersRoute
  '/_protected/orders': typeof ProtectedOrdersRoute
  '/_protected/payment-history': typeof ProtectedPaymentHistoryRoute
  '/_protected/payment-success': typeof ProtectedPaymentSuccessRoute
  '/_protected/payments': typeof ProtectedPaymentsRoute
  '/_protected/user-ticket': typeof ProtectedUserTicketRoute
  '/_protected/users': typeof ProtectedUsersRoute
  '/_protected/withdrawal-history': typeof ProtectedWithdrawalHistoryRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/home': typeof PublicHomeRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/refund-policy': typeof PublicRefundPolicyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_protected/mycourses/$id': typeof ProtectedMycoursesIdRoute
  '/_public/courses/$id': typeof PublicCoursesIdRoute
  '/_protected/mycourses/': typeof ProtectedMycoursesIndexRoute
  '/_public/courses/': typeof PublicCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/addcourses'
    | '/admin-dashboard'
    | '/admin-ticket'
    | '/all-orders'
    | '/all-users'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/mycontact'
    | '/myusers'
    | '/orders'
    | '/payment-history'
    | '/payment-success'
    | '/payments'
    | '/user-ticket'
    | '/users'
    | '/withdrawal-history'
    | '/about'
    | '/contact'
    | '/home'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms'
    | '/mycourses/$id'
    | '/courses/$id'
    | '/mycourses'
    | '/courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/addcourses'
    | '/admin-dashboard'
    | '/admin-ticket'
    | '/all-orders'
    | '/all-users'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/mycontact'
    | '/myusers'
    | '/orders'
    | '/payment-history'
    | '/payment-success'
    | '/payments'
    | '/user-ticket'
    | '/users'
    | '/withdrawal-history'
    | '/about'
    | '/contact'
    | '/home'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms'
    | '/mycourses/$id'
    | '/courses/$id'
    | '/mycourses'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/addcourses'
    | '/_protected/admin-dashboard'
    | '/_protected/admin-ticket'
    | '/_protected/all-orders'
    | '/_protected/all-users'
    | '/_protected/cart'
    | '/_protected/checkout'
    | '/_protected/dashboard'
    | '/_protected/mycontact'
    | '/_protected/myusers'
    | '/_protected/orders'
    | '/_protected/payment-history'
    | '/_protected/payment-success'
    | '/_protected/payments'
    | '/_protected/user-ticket'
    | '/_protected/users'
    | '/_protected/withdrawal-history'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/home'
    | '/_public/privacy-policy'
    | '/_public/refund-policy'
    | '/_public/terms'
    | '/_protected/mycourses/$id'
    | '/_public/courses/$id'
    | '/_protected/mycourses/'
    | '/_public/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/refund-policy': {
      id: '/_public/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof PublicRefundPolicyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/home': {
      id: '/_public/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PublicHomeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/withdrawal-history': {
      id: '/_protected/withdrawal-history'
      path: '/withdrawal-history'
      fullPath: '/withdrawal-history'
      preLoaderRoute: typeof ProtectedWithdrawalHistoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users': {
      id: '/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/user-ticket': {
      id: '/_protected/user-ticket'
      path: '/user-ticket'
      fullPath: '/user-ticket'
      preLoaderRoute: typeof ProtectedUserTicketRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payments': {
      id: '/_protected/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ProtectedPaymentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payment-success': {
      id: '/_protected/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof ProtectedPaymentSuccessRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payment-history': {
      id: '/_protected/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof ProtectedPaymentHistoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orders': {
      id: '/_protected/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ProtectedOrdersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/myusers': {
      id: '/_protected/myusers'
      path: '/myusers'
      fullPath: '/myusers'
      preLoaderRoute: typeof ProtectedMyusersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/mycontact': {
      id: '/_protected/mycontact'
      path: '/mycontact'
      fullPath: '/mycontact'
      preLoaderRoute: typeof ProtectedMycontactRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/checkout': {
      id: '/_protected/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ProtectedCheckoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cart': {
      id: '/_protected/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ProtectedCartRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/all-users': {
      id: '/_protected/all-users'
      path: '/all-users'
      fullPath: '/all-users'
      preLoaderRoute: typeof ProtectedAllUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/all-orders': {
      id: '/_protected/all-orders'
      path: '/all-orders'
      fullPath: '/all-orders'
      preLoaderRoute: typeof ProtectedAllOrdersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin-ticket': {
      id: '/_protected/admin-ticket'
      path: '/admin-ticket'
      fullPath: '/admin-ticket'
      preLoaderRoute: typeof ProtectedAdminTicketRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin-dashboard': {
      id: '/_protected/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/addcourses': {
      id: '/_protected/addcourses'
      path: '/addcourses'
      fullPath: '/addcourses'
      preLoaderRoute: typeof ProtectedAddcoursesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/courses/': {
      id: '/_public/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/mycourses/': {
      id: '/_protected/mycourses/'
      path: '/mycourses'
      fullPath: '/mycourses'
      preLoaderRoute: typeof ProtectedMycoursesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/courses/$id': {
      id: '/_public/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof PublicCoursesIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/mycourses/$id': {
      id: '/_protected/mycourses/$id'
      path: '/mycourses/$id'
      fullPath: '/mycourses/$id'
      preLoaderRoute: typeof ProtectedMycoursesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAddcoursesRoute: typeof ProtectedAddcoursesRoute
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedAdminTicketRoute: typeof ProtectedAdminTicketRoute
  ProtectedAllOrdersRoute: typeof ProtectedAllOrdersRoute
  ProtectedAllUsersRoute: typeof ProtectedAllUsersRoute
  ProtectedCartRoute: typeof ProtectedCartRoute
  ProtectedCheckoutRoute: typeof ProtectedCheckoutRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMycontactRoute: typeof ProtectedMycontactRoute
  ProtectedMyusersRoute: typeof ProtectedMyusersRoute
  ProtectedOrdersRoute: typeof ProtectedOrdersRoute
  ProtectedPaymentHistoryRoute: typeof ProtectedPaymentHistoryRoute
  ProtectedPaymentSuccessRoute: typeof ProtectedPaymentSuccessRoute
  ProtectedPaymentsRoute: typeof ProtectedPaymentsRoute
  ProtectedUserTicketRoute: typeof ProtectedUserTicketRoute
  ProtectedUsersRoute: typeof ProtectedUsersRoute
  ProtectedWithdrawalHistoryRoute: typeof ProtectedWithdrawalHistoryRoute
  ProtectedMycoursesIdRoute: typeof ProtectedMycoursesIdRoute
  ProtectedMycoursesIndexRoute: typeof ProtectedMycoursesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAddcoursesRoute: ProtectedAddcoursesRoute,
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminTicketRoute: ProtectedAdminTicketRoute,
  ProtectedAllOrdersRoute: ProtectedAllOrdersRoute,
  ProtectedAllUsersRoute: ProtectedAllUsersRoute,
  ProtectedCartRoute: ProtectedCartRoute,
  ProtectedCheckoutRoute: ProtectedCheckoutRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMycontactRoute: ProtectedMycontactRoute,
  ProtectedMyusersRoute: ProtectedMyusersRoute,
  ProtectedOrdersRoute: ProtectedOrdersRoute,
  ProtectedPaymentHistoryRoute: ProtectedPaymentHistoryRoute,
  ProtectedPaymentSuccessRoute: ProtectedPaymentSuccessRoute,
  ProtectedPaymentsRoute: ProtectedPaymentsRoute,
  ProtectedUserTicketRoute: ProtectedUserTicketRoute,
  ProtectedUsersRoute: ProtectedUsersRoute,
  ProtectedWithdrawalHistoryRoute: ProtectedWithdrawalHistoryRoute,
  ProtectedMycoursesIdRoute: ProtectedMycoursesIdRoute,
  ProtectedMycoursesIndexRoute: ProtectedMycoursesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicHomeRoute: typeof PublicHomeRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicRefundPolicyRoute: typeof PublicRefundPolicyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicCoursesIdRoute: typeof PublicCoursesIdRoute
  PublicCoursesIndexRoute: typeof PublicCoursesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicHomeRoute: PublicHomeRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicRefundPolicyRoute: PublicRefundPolicyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicCoursesIdRoute: PublicCoursesIdRoute,
  PublicCoursesIndexRoute: PublicCoursesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
